### ISSUE TITLE
Input buffer has issues with `<c-a>`, `<c-e>`, and `<BS>`

### ISSUE THREAD

**Issue by meijieru** [stevearc/dressing.nvim#2]
The original input method seems compatible with the `cmap`.
It would be helpful to have them here.

**Comment by stevearc** [comment]
It is possible to copy over the `cmap`s to the input modal, but it feels a little weird to me. The original input method uses `cmap` because it's happening in the command line. This window isn't the command line, it's just serving a purpose that was previously only done through the command line. I just added a specific filetype for the buffer (`DressingInput`) that will make it easy to add custom mappings. Will that work for you or do you really want all your `cmap`s available in the modal?

**Comment by meijieru** [comment]
It may help.
Currently, I use [tpope/vim-rsi](https://github.com/tpope/vim-rsi/blob/master/plugin/rsi.vim) so it would be better to enable them in simple way.
Maybe some presets could be provided?

**Comment by stevearc** [comment]
It looks like all of those cnoremaps have corresponding inoremaps. Is that not working? If your imaps aren't showing up in the modal that would certainly be a bug

**Comment by meijieru** [comment]
At least the following doesn't work
- `<c-a>`: it always inserts to the first character. For example, having text "abc", press `<c-a>`, insert "xyz", it would be "zyxabc"
- `<c-e>` does nothing.

**Comment by stevearc** [comment]
Okay, I'll test out that plugin and see if I can figure out what's going on

**Comment by stevearc** [comment]
Turns out this is a [bug in Neovim](https://github.com/neovim/neovim/issues/13715). There are several issues currently affecting the prompt buffer, the `<c-a>` causing text to be reversed is one, `<c-a>` breaking `<c-e>` is another (it works *until* you `<c-a>`), and there's a whole host of other problems. Fortunately there is [a PR up that fixes everything](https://github.com/neovim/neovim/pull/16421) (I built locally and verified). *Un*fortunately that means that the prompt buffer is going to be super hosed until the next neovim release, which might be a while.

I'm going to take a crack at re-implementing the input modal *without* using the prompt buffer. I think that's going to be the only way to avoid these issues for now.

**Comment by meijieru** [comment]
It works for me. Thx!

**Comment by frangio** [comment]
For anyone reading this now, `prompt_buffer` is no longer a setting.
