### ISSUE TITLE
telescope theme option not respected

### ISSUE THREAD

**Issue by goolord** [stevearc/dressing.nvim#21]
if i set `telescope.theme = "cursor"`, it will still display with the default "dropdown"

**Comment by stevearc** [comment]
I cannot reproduce this. Note that the "cursor" theme is nearly identical to the "dropdown" theme, except that it's positioned relative to the cursor instead of centered in the editor.

To make sure you don't have a typo or other placement error in the option, try changing it to `theme = "asdf"` and see if it spits out an error. If it doesn't, then there's an issue with the options format.

If you want to confirm that the theme values are getting passed through (or want to tweak them), you can pass them in directly as `theme = require('telescope.themes').get_cursor({})`
