### ISSUE TITLE
Making `code_action` next to the cursor.

### ISSUE THREAD

**Issue by B4mbus** [stevearc/dressing.nvim#48]
Currently `rename` opens nicely where the given symbol is, but code action, regardless of the chosen selector opens in the middle. 

Is it possible to make it open next to the cursor, where the code action is performed, like `lspsaga` does?

It would be way more convenient.

**Comment by stevearc** [comment]
This is configurable in the setup options. What backend are you using for select?

**Comment by B4mbus** [comment]
@stevearc Tbh I'm down to use any that will work for that, tho I'm most keen to use builtin and Telescope.

**Comment by stevearc** [comment]
To set the telescope UI to be relative to the cursor, use 
```lua
require("dressing").setup({
  select = {
    telescope = require("telescope.themes").get_cursor(),
  },
})
```
If you only want the UI to be relative to the cursor for code actions, use
```lua
require("dressing").setup({
  select = {
    get_config = function(opts)
      if opts.kind == "codeaction" then
        return {
          telescope = require("telescope.themes").get_cursor(),
        }
      end
    end,
  },
})
```
The configuration is similar if you want to use the built-in popup menu
```lua
require("dressing").setup({
  select = {
    builtin = {
      relative = "cursor",
    },
  },
})
```

**Comment by B4mbus** [comment]
@stevearc That's really nice, works fine, thanks.

**Comment by luetage** [comment]
First of all, great job on the plugin. It’s very useful. I’ve written several custom telescope pickers for myself in the past, but when I needed another simple one I just thought why go through the hassle when I can just use ui.select and dressing.nvim instead. I have the same issue now. I’m trying to use dressing’s config option to setup my picker with a different telescope theme, but I can’t really figure out how to use the `opts.kind` check to target my custom selection picker. It scans a directory, lists files and then executes code on the choice. I thought I just write that here instead of creating a new issue, it seems related.

**Comment by stevearc** [comment]
In general, I (and most maintainers) prefer new issues instead of comments on existing (especially closed) issues unless it's obvious that it's the exact same problem. It's easy to merge one discussion into another, but can be difficult to untangle two (or more) unrelated threads on the same issue. No worries about this time, just letting you know for the future 🙂

It sounds like you've handled the ask yourself, but for the reference of anyone reading this: the `kind` option is passed in by the callsite like so: https://github.com/neovim/neovim/blob/7a076306e4e35371160d1a5d09c92744b8461b57/runtime/lua/vim/lsp/buf.lua#L819-L826

Then you can use that inside of the `get_config` function or elsewhere to customize the behavior of `vim.ui.select`.

**Comment by luetage** [comment]
Ahh, thanks. I completely overlooked this parameter in help. Will use it for future select functions.
