### ISSUE TITLE
Borders are not rendered as nicely as in screenshot

### ISSUE THREAD

**Issue by lumbo7332** [stevearc/dressing.nvim#7]
Hi. The borders look disconnected and bad for me, but the look nice in the screenshots. What could be the issue?

Terminal: Konsole
Config: https://github.com/lumbo7332/dotfiles/tree/main/dot_config/nvim

![Screenshot_20211217_135621](https://user-images.githubusercontent.com/20866468/146612570-0814ad7e-f8f0-4d84-99a2-1b6c3d4a4a3d.png)

**Comment by stevearc** [comment]
This will be either your terminal or your font. I'd recommend trying out some different fonts to see if that changes things, or a different terminal. Some terminals have special-case rendering to make box-drawing characters look correct. I personally switched from alacritty to kitty because most fonts I tried look like this or worse in alacritty.

**Comment by lumbo7332** [comment]
Oh I understand. Thanks.
