### ISSUE TITLE
Attempt to index a boolean value

### ISSUE THREAD

**Issue by RomanoZumbe** [stevearc/dressing.nvim#78]
**Describe the bug**
Since the recent update I get an error when starting nvim on linux (not on windows though). The error message is:
E5113: Error while calling lua chunk: ...site/pack/packer/start/dressing.nvim/plugin/dressing.lua:1: attempt to index a boolean value

**System information**

- OS: linux
- Neovim version: 0.8.1
- Is this related to a specific `vim.ui.select` backend? If so, which one?
- Dressing config: After some testing I removed the config and the error is still persistent

```lua
-- Paste your call to require("dressing").setup(...) in here
```

**To Reproduce**

1. Install the plugin under linux
2.
3.

If possible, provide a minimal file that will trigger the issue (see
[tests/manual](https://github.com/stevearc/dressing.nvim/tree/master/tests/manual)
for examples of short ways to call `vim.ui.*`):

```
minimal code here
```

**Screenshots**

**Additional context**
I tried to find out what is going on and the problem is that the call to 'require("dressing")' in plugin\dressing is equated to true and not to a reference

**Comment by stevearc** [comment]
This is going to be because of some conflict you have in your config. If `require("dressing")` is returning true, it either means that you have another module in your runtimepath at `lua/dressing.lua` or `lua/dressing/init.lua` that _is_ returning a boolean (and is resolved earlier than the one in the plugin), or it means that you've monkey patched `require` and it's doing something very unexpected.

**Comment by RomanoZumbe** [comment]
Oh man, what a shitty mistake of mine. There was indeed a copy in the root of my nvim folder. It was my previous settings file for the plugin that I backed up before setting the new win_options. Somehow I seem to have forgotten to change the location. Sorry for the unnecessary work!
